repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # Check for files larger than 10MB
        args: [ '--maxkb=10000' ]
      - id: check-ast # Check python files for syntax errors
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: pretty-format-json # Pretty format JSON files
        args: [ --autofix ]
      - id: check-yaml # Check YAML files for syntax errors
      - id: detect-private-key # Check for private keys
      - id: detect-aws-credentials # Check for AWS credentials
        args: [ --allow-missing-credentials ] # Allow hook to pass if AWS credentials are not found
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace # Trims trailing whitespace
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          [ "--verbose", "--skip-string-normalization", "--line-length", "120" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [ "-i", "--quote", "'" ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-quotes ]
        args:
          [
            "--inline-quotes",
            "single",
            "--count",
            "--show-source",
            "--statistics",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]

  - repo: https://github.com/dosisod/refurb
    rev: v1.25.0
    hooks:
      - id: refurb
        language_version: python3.10

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter

  # python docstring coverage checking
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0 # or master if you're bold
    hooks:
      - id: interrogate
        args:
          [
            --verbose,
            --fail-under=80,
            --ignore-init-module,
            --ignore-init-method,
            --ignore-module,
            --ignore-nested-functions,
            -vv,
          ]

  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          [
            --in-place,
            --wrap-summaries=120,
            --wrap-descriptions=120,
            --style=google,
            --black,
          ]